### PR TITLE
Additional LIN and FlexRay Tests

### PR DESCRIPTION
**Pull request by douglasnorman**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-xnet-system-tests/blob/master/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-xnet-system-tests/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

It adds more tests for LIN and FlexRay:

1. test LIN Data Logging Loopback.vi
2. test LIN Incoming from External XNET.vi
3. test LIN Sporadic Loopback.vi
4. test LIN 64 Bit Raw Data Loopback.vi
5. test FlexRay 64 Bit Raw Data Loopback.vi

### Why should this Pull Request be merged?

To expand our ATS coverage of LIN and FlexRay.

### What testing has been done?

All tests were run on the ATS.

### CODE REVIEW

**Comment by rtzoeller** [comment]
# PR overhead
- [ ] Can you update the pull request title to something other than the (space replaced) branch name?

- [ ] Please check the contributing bit at the top of the PR description. It's less important for internal contributors since it's implicit, but it should either be checked or removed entirely.

# VI comments
- [ ] Several VIs modified in this PR appear to only have had their versions changed. Ideally, all VIs in this repo would be in one LabVIEW version (probably LV 2020), and PRs would only include VIs which have had substantive changes. I'm going to mass-save everything to LV 2020 (with @niphilj's blessing) in a subsequent PR, so it's not a huge deal, but to make it easier to understand which files have actually changed it'd be nice if these files were reset.

I believe the following VIs can be reset:
	- `FlexRay Loopback/test FlexRay Cyclic Loopback.vi`
	- `FlexRay Loopback/testExample.vit`
	- `LIN Loopback/text LIN Unconditional Loopback.vi`
	- `LIN Loopback/testExample.vit`

Let me know if you see some that I have missed. To reset individual files to the version on `master` (make sure you have the latest version of master first!), you can run the following commands:
```
git checkout master -- filename1 filename2
git commit -m "Revert files to version on master"
git push
```

- [ ] `LIN Data Logging Loopback.vi`: Can you explain why we need to bitwise-AND with 0x1FFFFFFF?

- [ ] `test LIN Incoming from External XNET.vi`: It seems like there should be a delay in this loop. Otherwise it seems like we'd just read the same value 10x in quick succession? Similarly, should we be checking that we're getting unique values on each iteration?
image

- [ ] `test CAN Incoming from External XNET.vi` has the same issues as `test LIN Incoming from External XNET.vi`, and should be fixed as well.


# No action required
- [x] `temp_VI_UnderTest.vi`: These get auto-generated by the class template, but we really don't need/want them. We should remove them and update the test templates not to call them. I'll likely put up a PR to remove them from all of the test classes (since it affects classes not touched by this PR), but moving forward we should delete them as we go.

- [x] There are a mix of source-separated and source-not-separated VIs. I'll put up a PR to fix this globally, but moving forward we should make sure source is separated for all new VIs.

- [x] It'd be easier to review if this PR was split up a bit. In the future, consider submitting several smaller PRs as you go. For example, this PR could either be submitted as a PR per test class, or a PR per protocol.

- [x] In the future, consider using multiple assertions, rather than ANDing things together and then asserting. This makes it easier to debug, because custom messages can tell us which assertion failed.
image

**Comment by douglasnorman** [comment]
Made PR overhead changes.

**Comment by douglasnorman** [comment]
>LIN Data Logging Loopback.vi: Can you explain why we need to bitwise-AND with 0x1FFFFFFF?

I cannot. That code was lifted from a shipping example:
LabVIEW 2020\examples\nixnet\examples.llb\Display TDMS Logfile as LIN Frames.vi

which calls:
LabVIEW 2020\examples\nixnet\NI-XNET Frame Conversion and Logfile.llb\NI-XNET Frame&Log - Convert Single Frame (Raw to LIN).vi

**Comment by douglasnorman** [comment]
>Several VIs modified in this PR appear to only have had their versions changed. Ideally, all VIs in this repo would be in one LabVIEW version (probably LV 2020), and PRs would only include VIs which have had substantive changes. I'm going to mass-save everything to LV 2020 (with @niphilj's blessing) in a subsequent PR, so it's not a huge deal, but to make it easier to understand which files have actually changed it'd be nice if these files were reset.

I reverted the four files, and did not see any others to revert.

**Comment by rtzoeller** [comment]
> I cannot. That code was lifted from a shipping example

Can you add a comment saying that to the test? Thanks!

**Comment by douglasnorman** [comment]
>test LIN Incoming from External XNET.vi: It seems like there should be a delay in this loop. Otherwise it seems like we'd just read the same value 10x in quick succession? Similarly, should we be checking that we're getting unique values on each iteration?
>test CAN Incoming from External XNET.vi has the same issues as test LIN Incoming from External XNET.vi, and should be fixed as well.
>Can you add a comment saying that to the test? Thanks!

I added a delay in the For Loop of ther Incoming tests.  I don't think checking for unique values makes sense - it would set us up for trying to coordinate timing between I/O, since the random number could in theory get duplicated.

I added a note in the data logging test regarding the source of the code snippet that uses bitwise-AND with 0x1FFFFFFF.

**Comment by niphilj** [comment]
> > I cannot. That code was lifted from a shipping example
> 
> Can you add a comment saying that to the test? Thanks!

Exactly, at least adding that in a comment on the Block Diagram that reference the source.

**Comment by niphilj** [comment]
> There are a mix of source-separated and source-not-separated VIs. I'll put up a PR to fix this globally, but moving forward we should make sure source is separated for all new VIs.

Agreed. And there is a button on the project's properties that easily allows you to do that to all VIs in one go.

**Comment by rtzoeller** [comment]
> Agreed. And there is a button on the project's properties that easily allows you to do that to all VIs in one go.

But unfortunately it doesn't work for .vit files, of which we have many. Those have to be manually marked.

**Comment by rtzoeller** [comment]
> I added a delay in the For Loop of the Incoming tests.

My inclination is that 10ms is too small of a delay to get new values back from VeriStand each cycle. I can't recall the exact refresh rate of data through the gateway, but it's not that high.

Can you confirm the values are actually updating between loop iterations (e.g. by probing the wire)? I think the delays should probably be much larger, e.g. 250ms.

image

>  I don't think checking for unique values makes sense - it would set us up for trying to coordinate timing between I/O, since the random number could in theory get duplicated.

I'm fine not checking this in the actual test, but I'd like us to validate before submitting that we are getting roughly 10 unique data points (one per loop iteration). With the delay at 10ms, I don't think that is the case.

**Comment by niphilj** [comment]
- [ ] LIN Data Logging Loopback.vi, small request: I'm generally not a fan of using the ".." option for a case structure wired to a enum. In your case, it's |"Linux64CRIO".."LinuxARM"|, and the reason is it's difficult to know what other cases are covered here. I would prefer using a comma to make it more obvious |"Linux64CRIO", "Linux64PXI", "LinuxARM"| for readability.

**Comment by douglasnorman** [comment]
>LIN Data Logging Loopback.vi, small request: I'm generally not a fan of using the ".." option for a case structure wired to a enum. In your case, it's |"Linux64CRIO".."LinuxARM"|, and the reason is it's difficult to know what other cases are covered here. I would prefer using a comma to make it more obvious |"Linux64CRIO", "Linux64PXI", "LinuxARM"| for readability.

LabVIEW seems to prefer the ..
When I type them individually comma separated, LabVIEW changes it back to ..

**Comment by douglasnorman** [comment]
>I'm fine not checking this in the actual test, but I'd like us to validate before submitting that we are getting roughly 10 unique data points (one per loop iteration). With the delay at 10ms, I don't think that is the case.

I changed the loop rates to 500ms.

**Pull request merged**
