### PR TITLE
Add tests for LIN No Response Frame fix

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-xnet-system-tests/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Add regression tests to verify fix for LIN ports sending No Response frames during initialization.

### Why should this Pull Request be merged?

To capture regressions for AzDO bug 114970.

### What testing has been done?

Ran tests locally and confirmed they fail without the changes for 114970 and pass with them.

### CODE REVIEW

**Comment by rtzoeller** [comment]
@niphilj we have our first example of tests that we would potentially want in a release branch, since this fix should be going into 2020 R4 and not R3. Feel free to break out the "I told you so"s. 😉

**Comment by Karl-G1** [comment]
To pile on the I told you so's, we may want to run tests on different combos of VS/driver software down the line as well... Would release branches help, or should we start by explicitly marking minimum versions in the Open VS Connection VI to avoid running tests on new fixes/features?

**Comment by rtzoeller** [comment]
@Karl-G1 the minimum version parameter currently only takes a major year version, so that doesn't work (original use was to avoid running SLSC tests in 2016). 

We can either create release branches and update the runner to take advantage of that, or come up with an alternative. Just marking the tests as 'skip' (which is what Open VeriStand Connection would do) would cause them to show up as failures, which isn't ideal.

**Comment by Karl-G1** [comment]
Good point, as this particular change would just affect a minor release version anyway. Let's punt on that one for now.

**Comment by rtzoeller** [comment]
@niphilj the changelist for the XNET functionality has been submitted, so this can be reviewed.

**Review by niphilj — APPROVED** [review]
- [ ] Group Frames by ID.vi.png
FYI: You can use an in-place structure when simply modifying the content of a Map.

**Review by buckd — APPROVED** [review]

**Pull request merged**
