### PR TITLE
Adding three tests: FlexRay loopback, LIN loopback, Status Channels basic read

### PR DESCRIPTION
**Pull request by douglasnorman**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-xnet-system-tests/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

It adds three tests:
LIN - basic loopback
FlexRay - basic loopback
CAN Status Channels - basic loopback with status channels read

### Why should this Pull Request be merged?

These tests are needed, so the ATS covers this functionality.

### What testing has been done?

All of these tests have been successfully run on a dev or test VM.

### CODE REVIEW

**Comment by niphilj** [comment]
- [ ] __CAN Cyclic and Event Triggered Tests\test CAN Cyclic Loopback with Status Channels.vi__ if the 2 string array constants for the status channels are always the same, could the one instance of that constant be used instead of having the copies. And if that gets done, I would also wire the "8" constant when checking the size to both equals. (Good luck making the wires look nice)

**Comment by douglasnorman** [comment]
Karl - I'll delete the "temp" VIs nnnnnext time I'm editing tests. I think all the classes have one.
Ryan - the reason I test the size, is because an empty array is returned if a channel name is wrong.
Phil - your statement is true, but is it worth spending the time to edit a test?

I'm voting no changes for now unless any one of you say they are required.

**Comment by rtzoeller** [comment]
> the reason I test the size, is because an empty array is returned if a channel name is wrong.

Does it return an error if a channel name is wrong? I would hope so, in which case we still don't need the size check. If it doesn't, that's really unfortunate...

**Comment by douglasnorman** [comment]
Yes it does throw an error. I'll go ahead and edit as you suggest.

**Pull request merged**
